### PR TITLE
Fixed error codes

### PR DESCRIPTION
**Pull request by norman784**
For some reason the app hangs if some file isn't found with the positive error codes

### CODE REVIEW

**Comment by norman784** [comment]
@yan-foto check it when you can please, also will be cool to upload to npmjs, thanks

**Comment by revington** [comment]
@norman784 Because it looks like this project is no longer maintained I created my own an included your changes https://github.com/revington/yet-another-electron-pug

**Comment by yan-foto** [comment]
@revington stealing code is one thing, but advertising it on the original repository is a whole new level unknown to me.

**Comment by revington** [comment]
@yan-foto what? You released your code under the MIT license. I did not steal anything. 
You should be happy that someone else forked (yes, this is the correct term) your project. And I did it because you have ignored the issues reported by other users (including me). So I forked your project and fixed the stuff and of course I told those users, the ones you failed, that there was an alternative. 

Is this totally unknown to you? Welcome to the free libre open source software.

**Comment by yan-foto** [comment]
I think you misunderstood "free"! The proper approach would be to contribute or to become a maintainer. If you copy exact snippets of codes, the least you can to is to link to the original source and mention original authors as an act of courtesy. If you want to discuss on the terminology, you **did not** fork it. You created a new repository and proudly copy/pasted everything. In this case we are talking about trivialities, which really don't matter. But going on like this would not bring you much far in the community.

Is this totally unknown to you? Welcome to the world of decency.

**Pull request merged**
