### PR TITLE
Fixed app.on('ready') issue

### PR DESCRIPTION
**Pull request by brtthomp**
Electron-pug only registers the interceptor through app.on('ready').  I was having issues with this because the app was already in the 'ready' state by the time pug was being registered.  I added a check to see if the app is already ready, and if so, it will register the interceptor.  If the app is not ready it will work as before.

### CODE REVIEW

**Comment by yan-foto** [comment]
Thanks 👍 I will look into it, as soon as I get some free time!

**Comment by revington** [comment]
@brtthomp  Because it looks like this project is no longer maintained I created my own an included your changes https://github.com/revington/yet-another-electron-pug

**Comment by yan-foto** [comment]
@revington I can add you as maintainer here if you'd like.

**Comment by revington** [comment]
@yan-foto Thanks for the offer but I already spent some time creating the repo, setting up coveralls and other stuff.

**Pull request merged**
