### PR TITLE
Fixing error in callbacks

### PR DESCRIPTION
**Pull request by gamelaster**

### CODE REVIEW

**Comment by yan-foto** [comment]
Sounds correct! Will fix after holidays. Cheers :+1:

**Comment by yan-foto** [comment]
Have you already tried this? I remember that I had this issue from the beginning (also with positive numbers): regardless of error code I always get `Not allowed to load local resource`.

I used positive numbers because I saw some other packages doing the same thing. But I went through chromium's source code and I am pretty sure that you should use negative codes. However, I cannot explain why I get the same error in dev tools. any ideas?

**Comment by gamelaster** [comment]
I used this in electron-ejs and it's working nice
(I will send photo when I arrive home)

**Comment by gamelaster** [comment]
image
https://github.com/jmjuanes/electron-ejs/blob/master/index.js#L47

**Comment by yan-foto** [comment]
That is interesting. Could you do me a favor and check if it works with your setup? (w/ `electron-pug`)

**Comment by norman784** [comment]
The app hangs if some files are not found, and the issue its the error codes, @yan-foto you should accept this pull request

**Comment by yan-foto** [comment]
@norman784 There are conflicts (PR from a year ago) and I don't have time to fix this. Feel free to contribute or take over the project completely.

**Comment by norman784** [comment]
cool, I will make a new pull request

**Comment by gamelaster** [comment]
@norman784 I only now saw your comments here, and now already you pulled #9 , so I closing this

**Pull request closed without merging**
